kind: Service
apiVersion: v1
metadata:
  name: freebox-exporter-rs
  namespace: monitoring
spec:
  selector:
    app: freebox-exporter-rs
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 9100
    targetPort: 9100