apiVersion: v1
kind: ConfigMap
metadata:
  name: freebox-exporter-rs-config
  namespace: monitoring
  labels:
    app: freebox-exporter-rs
data:
  config.toml: |
    [api]
    # Refresh wait interval in seconds, application will send requests to the freebox host on each refresh iteration
    # This does not affect prometheus scrap agents, application will use cached values between calls
    # Remark:
    #   more you set API exposition (c.f: [metrics] section) more requests will be sent,
    #   setting a too low interval between refreshs could lead to request rate limiting from freebox host
    refresh = 5

    [metrics]
    # Exposes connection
    connection = true
    # Exposes lan, this option may not work in bridge_mode
    lan = true
    # Exposes lan browser, this option does not work in bridge_mode
    lan_browser = true
    # Exposes switch, this option may not work properly in bridge_mode
    switch = true
    # Exposes wifi
    wifi = true
    # Exposes dhcp
    dhcp = true
    # Exposes system
    system = true
    # Sets metrics prefix, it cannot be empty
    # Warning if you are using the exporter Grafana board, changing this value will cause the board to be unable to retrieve data if you do not update it
    prefix = "fbx_exporter"

    [core]
    # Specify where to store data for exporter such as APP_TOKEN, logs, etc.
    data_directory = "/var/log/freebox-exporter-rs"
    # Specify which TCP port to listen to, for the /metrics HTTP endpoint
    port = 9100

    [log]
    # Specify which log level to use
    # Acceptable values :
    #   * "Off"     : A level lower than all log levels
    #   * "Error"   : Corresponds to the `Error` log level
    #   * "Warn"    : Corresponds to the `Warn` log level
    #   * "Info"    : Corresponds to the `Info` log level
    #   * "Debug"   : Corresponds to the `Debug` log level
    #   * "Trace"   : Corresponds to the `Trace` log level
    level = "Info"
    # Specify how long application should keep compressed log files, value is in days
    retention = 31