{
 "title": "freebox-exporter-rs",
 "description": "Grafana board for the freebox exporter https://github.com/shackerd/freebox-exporter-rs",
 "tags": [
  "freebox-exporter-rs",
  "freebox"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "switch_port", "label": "Switch Ports", "query": { "query": "label_values(port)" } },
   { "name": "wlan_band", "label": "Wi-Fi Band", "query": { "query": "label_values(band)" } },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(fbx_exporter_connection_bytes_down,job)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(fbx_exporter_connection_bytes_down,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Wi-Fi load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fbx_exporter_wifi_rx_percent{instance=\"$node\", job=\"$job\", band=~\"$wlan_band\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fbx_exporter_connection_rate_down{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Down"
    },
    {
     "expr": "fbx_exporter_connection_rate_up{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Packets rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (fbx_exporter_switch_stats_rx_packets_rate{instance=\"$node\", job=\"$job\"})",
     "legendFormat": "RX"
    },
    {
     "expr": "sum by(__name__) (fbx_exporter_switch_stats_tx_packets_rate{instance=\"$node\", job=\"$job\"})",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Total online devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(fbx_exporter_lan_browser_device{instance=\"$node\", job=\"$job\"}>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Eth. ports",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fbx_exporter_switch_port_status{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Eth. ports speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fbx_exporter_switch_port_speed{instance=\"$node\", job=\"$job\"} > 0",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fbx_exporter_connection_bytes_up{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Up"
    },
    {
     "expr": "fbx_exporter_connection_bytes_down{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Traffic over 1m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(fbx_exporter_connection_bytes_down{instance=\"$node\", job=\"$job\"}[1m])",
     "legendFormat": "Down"
    },
    {
     "expr": "delta(fbx_exporter_connection_bytes_up[1m])",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Traffic repartition over 1m",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(fbx_exporter_connection_bytes_up{instance=\"$node\", job=\"$job\"}[1m])",
     "legendFormat": "Up"
    },
    {
     "expr": "delta(fbx_exporter_connection_bytes_down{instance=\"$node\", job=\"$job\"}[1m])",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Wifi traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(band) (fbx_exporter_wifi_station_rx_bitrate{instance=\"$node\", job=\"$job\", band=~\"$wlan_band\"})",
     "legendFormat": "Rx: {{band}}"
    },
    {
     "expr": "sum by(band) (fbx_exporter_wifi_station_tx_bitrate{instance=\"$node\", job=\"$job\", band=~\"$wlan_band\"})",
     "legendFormat": "Tx: {{band}}"
    }
   ]
  },
  {
   "title": "CPU(s) temperatures",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fbx_exporter_system_temp_cpub{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "CPU B"
    },
    {
     "expr": "fbx_exporter_system_temp_cpum{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "CPU M"
    },
    {
     "expr": "fbx_exporter_system_temp_sw{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "SW"
    }
   ]
  },
  {
   "title": "Firmware version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fbx_exporter_system_firmware_version{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{firmware_version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fbx_exporter_system_uptime_val{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wi-Fi devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(ap_name) (fbx_exporter_wifi_station_active{instance=\"$node\", job=\"$job\"})",
     "legendFormat": "{{ap_name}}"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fbx_exporter_system_fan_rpm{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Fan"
    }
   ]
  },
  { "title": "News", "type": "news", "gridPos": { "h": 6, "w": 7, "x": 6, "y": 11 } },
  {
   "title": "ISP link state",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fbx_exporter_system_box_authenticated{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Authenticated"
    },
    {
     "expr": "fbx_exporter_connection_ftth_sfp_has_signal{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "SFP Signal"
    },
    {
     "expr": "fbx_exporter_connection_ftth_sfp_pwr_rx{instance=\"$node\", job=\"$job\"} / 100",
     "legendFormat": "Signal Quality"
    },
    {
     "expr": "fbx_exporter_connection_ipv4{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Public address : {{ipv4}}"
    }
   ]
  },
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Fan",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "fbx_exporter_system_fan_rpm{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "fbx_exporter_system_temp_cpub{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "CPU B"
    },
    {
     "expr": "fbx_exporter_system_temp_cpum{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "CPU M"
    },
    {
     "expr": "fbx_exporter_system_temp_sw{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "SW"
    }
   ]
  },
  { "title": "FTTH (SFP)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "RX power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "fbx_exporter_connection_ftth_sfp_pwr_rx{instance=\"$node\", job=\"$job\"}/100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "fbx_exporter_connection_ftth_sfp_pwr_tx{instance=\"$node\", job=\"$job\"}/100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SFP info",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fbx_exporter_connection_ftth_sfp_has_signal{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Signal"
    },
    {
     "expr": "fbx_exporter_connection_ffth_sfp_present{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Present"
    },
    {
     "expr": "fbx_exporter_connection_ffth_sfp_alim_ok{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Powered"
    }
   ]
  },
  {
   "title": "Current signal quality",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fbx_exporter_connection_ftth_sfp_pwr_rx{instance=\"$node\", job=\"$job\"}/100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "fbx_exporter_connection_rate_up{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Up"
    },
    {
     "expr": "fbx_exporter_connection_rate_down{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Bandwidth per port",
   "type": "timeseries",
   "description": "Port(s) bandwidth",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "fbx_exporter_switch_stats_rx_bytes_rate{instance=\"$node\", job=\"$job\", port=~\"$switch_port\"}",
     "legendFormat": "{{port}} :: Rx"
    },
    {
     "expr": "fbx_exporter_switch_stats_tx_bytes_rate{instance=\"$node\", job=\"$job\", port=~\"$switch_port\"}",
     "legendFormat": "{{port}} :: Tx"
    }
   ]
  },
  {
   "title": "Traffic usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fbx_exporter_connection_bytes_up{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Up"
    },
    {
     "expr": "fbx_exporter_connection_bytes_down{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Traffic over 1m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(fbx_exporter_connection_bytes_down{instance=\"$node\", job=\"$job\"}[1m])",
     "legendFormat": "Down"
    },
    {
     "expr": "delta(fbx_exporter_connection_bytes_up{instance=\"$node\", job=\"$job\"}[1m])",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Packets by types over 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "targets": [
    {
     "expr": "sum by(__name__) (delta(fbx_exporter_switch_stats_rx_good_packets{instance=\"$node\", job=\"$job\", port=~\"$switch_port\"}[1m]))",
     "legendFormat": "Good"
    },
    {
     "expr": "sum by(__name__) (delta(fbx_exporter_switch_stats_tx_broadcast_packets{instance=\"$node\", job=\"$job\", port=~\"$switch_port\"}[1m]))",
     "legendFormat": "Broadcast "
    },
    {
     "expr": "sum by(__name__) (delta(fbx_exporter_switch_stats_rx_multicast_packets{instance=\"$node\", job=\"$job\", port=~\"$switch_port\"}[1m]))",
     "legendFormat": "Multicast"
    },
    {
     "expr": "sum by(__name__) (delta(fbx_exporter_switch_stats_rx_jabber_packets{instance=\"$node\", job=\"$job\", port=~\"$switch_port\"}[1m]))",
     "legendFormat": "Jabber"
    },
    {
     "expr": "sum by(__name__) (delta(fbx_exporter_switch_stats_rx_err_packets{instance=\"$node\", job=\"$job\", port=~\"$switch_port\"}[1m]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum by(__name__) (delta(fbx_exporter_switch_stats_rx_unicast_packets{instance=\"$node\", job=\"$job\", port=~\"$switch_port\"}[1m]))",
     "legendFormat": "Unicast"
    },
    {
     "expr": "sum by(__name__) (delta(fbx_exporter_switch_stats_rx_fcs_packets{instance=\"$node\", job=\"$job\", port=~\"$switch_port\"}[1m]))",
     "legendFormat": "Fcs"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "targets": [
    {
     "expr": "fbx_exporter_switch_stats_rx_packets_rate{instance=\"$node\", job=\"$job\", port=~\"$switch_port\"}",
     "legendFormat": "{{port}} :: Rx"
    },
    {
     "expr": "fbx_exporter_switch_stats_tx_packets_rate{instance=\"$node\", job=\"$job\", port=~\"$switch_port\"}",
     "legendFormat": "{{port}} :: Tx"
    }
   ]
  },
  { "title": "DHCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "DHCP Dynamic Leases Remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "fbx_exporter_dhcp_lease_remaining{instance=\"$node\", job=\"$job\", is_static=\"false\"}",
     "legendFormat": "{{hostname}} ({{ip}})"
    }
   ]
  },
  {
   "title": "DHCP Last Assigned Leases",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "fbx_exporter_dhcp_assign_time{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Wifi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Wifi Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fbx_exporter_wifi_rx_bss_percent{instance=\"$node\", job=\"$job\", band=~\"$wlan_band\"}",
     "legendFormat": "{{name}} Bandwith"
    },
    {
     "expr": "fbx_exporter_wifi_rx_percent{instance=\"$node\", job=\"$job\", band=~\"$wlan_band\"}",
     "legendFormat": "{{name}} Load"
    },
    {
     "expr": "fbx_exporter_wifi_busy_percent{instance=\"$node\", job=\"$job\", band=~\"$wlan_band\"}",
     "legendFormat": "{{name}} Total load"
    }
   ]
  },
  {
   "title": "Stations bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "fbx_exporter_wifi_station_rx_bitrate{instance=\"$node\", job=\"$job\", band=~\"$wlan_band\"}",
     "legendFormat": "Rx: {{ipv4}}"
    },
    {
     "expr": "fbx_exporter_wifi_station_tx_bitrate{instance=\"$node\", job=\"$job\", band=~\"$wlan_band\"}",
     "legendFormat": "Tx: {{ipv4}}"
    }
   ]
  },
  {
   "title": "Stations Signal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "fbx_exporter_wifi_station_signal{instance=\"$node\", job=\"$job\", band=~\"$wlan_band\"}",
     "legendFormat": "{{ipv4}} ({{band}})"
    }
   ]
  },
  {
   "title": "Stations traffic over 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(fbx_exporter_wifi_station_rx_bytes{instance=\"$node\", job=\"$job\", band=~\"$wlan_band\"}[1m])",
     "legendFormat": "Rx: {{ipv4}} ({{ap_name}})"
    },
    {
     "expr": "delta(fbx_exporter_wifi_station_tx_bytes{instance=\"$node\", job=\"$job\", band=~\"$wlan_band\"}[1m])",
     "legendFormat": "Tx: {{ipv4}} ({{ap_name}})"
    }
   ]
  },
  {
   "title": "Channel Usage (Noise level)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "fbx_exporter_wifi_channel_usage{instance=\"$node\", job=\"$job\", band=~\"$wlan_band\"}",
     "legendFormat": "[{{channel}}] {{band}}"
    }
   ]
  },
  {
   "title": "Neighbors Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "fbx_exporter_wifi_neighbors_access_point{instance=\"$node\", job=\"$job\", band=~\"$wlan_band\"}",
     "legendFormat": "[{{channel}}] {{bssid}} {{ssid}} {{band}}"
    }
   ]
  },
  {
   "title": "Station activeness",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "fbx_exporter_wifi_station_active{instance=\"$node\", job=\"$job\", band=~\"$wlan_band\"}",
     "legendFormat": "{{primary_name}} ({{mac}}) ({{ap_name}})"
    }
   ]
  },
  {
   "title": "Station Inactivity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "fbx_exporter_wifi_station_inactive{instance=\"$node\", job=\"$job\", band=~\"$wlan_band\"}",
     "legendFormat": "{{ipv4}} ({{ap_name}})"
    }
   ]
  },
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Connections",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "fbx_exporter_lan_browser_device{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{primary_name}} ({{l2ident_id}})"
    }
   ]
  },
  {
   "title": "Dispatch per iface",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fbx_exporter_lan_browser_iface_hosts{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}